services:
  frontend:
    image: 029180756761.dkr.ecr.sa-east-1.amazonaws.com/velasco-frontend:latest
    ports:
      - "80:80"
    restart: always
    networks:
      - velasco-network

networks:
  velasco-network:
    external: true
